In [75]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [76]:
csv_file = "cleanedICPSR.csv"
df = pd.read_csv(csv_file)
df.head()

Unnamed: 0 Race of Offender Age at Execution              Name of Offender  \
0           0            White                   NORMAN ELI                     
1           1            White                   WOODS JOHN                     
2           2            Black                   GAMARRA CHARLES                
3           3            Black                   DESAYAS VICTORIANO             
4           4            Black                   NOREAGO FRANCISCO              

  Place of Execution Jurisdiction of Exection Crimes Committed  \
0                  2                        4               01   
1                  4                        6               44   
2                  2                        2               13   
3                  2                        2               01   
4                  2                        2               01   

  Method of Execution Day Month  Year  State  County  Sex      CountyName  \
0             Hanging  19    12  1812      1      89  NaN  Madison County   
1                Shot  06    02  1814      1       0  NaN       York city   
2             Hanging  19    05  1820      1      97  NaN   Mobile County   
3             Hanging  19    05  1820      1      97  NaN   Mobile County   
4             Hanging  30    05  1822      1      97  NaN   Mobile County   

  StateName  
0   Alabama  
1   Alabama  
2   Alabama  
3   Alabama  
4   Alabama

In [82]:
#df['DataFrame Column'] = df['DataFrame Column'].astype(float)
#df['Place of Execution'] = pd.to_numeric(df['Place of Execution'],errors='coerce').round()
#df['Jurisdiction of Exection'] = pd.to_numeric(df['Jurisdiction of Exection'],errors='coerce').round()
df['Crimes Committed'] = pd.to_numeric(df['Crimes Committed'],errors='coerce').round()

In [88]:
df.dropna()

Empty DataFrame
Columns: [Unnamed: 0, Race of Offender, Age at Execution, Name of Offender, Place of Execution, Jurisdiction of Exection, Crimes Committed, Method of Execution, Day, Month, Year, State, County, Sex, CountyName, StateName]
Index: []

In [89]:
#dataset = df[['Place of Execution', 'Jurisdiction of Exection','Crimes Committed', 'Year', 'State', 'County']]
dataset = df[['Crimes Committed', 'Year', 'State', 'County']]

In [90]:
#df.County.unique()
dataset.head()

Crimes Committed  Year  State  County
0               1.0  1812      1      89
1              44.0  1814      1       0
2              13.0  1820      1      97
3               1.0  1820      1      97
4               1.0  1822      1      97

In [91]:
dataset_array = dataset.values
print(dataset_array.dtype)
print(dataset_array)

float64
[[1.000e+00 1.812e+03 1.000e+00 8.900e+01]
 [4.400e+01 1.814e+03 1.000e+00 0.000e+00]
 [1.300e+01 1.820e+03 1.000e+00 9.700e+01]
 ...
 [1.100e+01 2.001e+03 5.300e+01 6.100e+01]
 [1.100e+01 2.000e+03 5.400e+01 1.830e+02]
 [2.600e+01 1.992e+03 5.600e+01 0.000e+00]]


In [92]:
# Create a kmeans model using k = 12
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=12)

# Fit the model to the data
kmeans.fit(dataset)

# Use the data to predict the clusters
# save the predictions as `predicted_clusters`
predicted_clusters = kmeans.predict(dataset)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').