In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [14]:
csv_file = "cleanedICPSR.csv"
df = pd.read_csv(csv_file)
df.head()

Unnamed: 0 Race of Offender Age at Execution              Name of Offender  \
0           0            White                   NORMAN ELI                     
1           1            White                   WOODS JOHN                     
2           2            Black                   GAMARRA CHARLES                
3           3            Black                   DESAYAS VICTORIANO             
4           4            Black                   NOREAGO FRANCISCO              

  Place of Execution Jurisdiction of Exection Crimes Committed  \
0                  2                        4               01   
1                  4                        6               44   
2                  2                        2               13   
3                  2                        2               01   
4                  2                        2               01   

  Method of Execution Day Month  Year  State  County  Sex      CountyName  \
0             Hanging  19    12  1812      1      89  NaN  Madison County   
1                Shot  06    02  1814      1       0  NaN       York city   
2             Hanging  19    05  1820      1      97  NaN   Mobile County   
3             Hanging  19    05  1820      1      97  NaN   Mobile County   
4             Hanging  30    05  1822      1      97  NaN   Mobile County   

  StateName  
0   Alabama  
1   Alabama  
2   Alabama  
3   Alabama  
4   Alabama

In [15]:
#Clean Dataset for ML
df['Crimes Committed'].replace('  ', np.nan, inplace=True)
df = df[pd.notnull(df['Crimes Committed'])]
#df

Unnamed: 0 Race of Offender Age at Execution  \
0               0            White                    
1               1            White                    
2               2            Black                    
3               3            Black                    
4               4            Black                    
5               5            White               60   
6               6            White                    
7               7            Black                    
8               8            White                    
9               9            White                    
10             10            White                    
11             11            Black                    
12             12            Black                    
13             13            White                    
14             14            White                    
15             15            Black                    
16             16            Black                    
17             17            White                    
18             18            Black                    
19             19            White                    
20             20            Black                    
21             21            Black                    
22             22  Native American                    
23             23  Native American                    
24             24            White                    
25             25            Black                    
26             26            White                    
27             27            Black                    
28             28            Black                    
29             29            Black                    
...           ...              ...              ...   
15238       15238            White               37   
15239       15239            White               57   
15240       15240            Black               36   
15241       15241            White               29   
15242       15242            White               26   
15243       15243            White               38   
15244       15244            White               33   
15245       15245            Black               26   
15246       15246            White               51   
15247       15247            Black               27   
15248       15248            Black               32   
15249       15249            Black               29   
15250       15250            White               26   
15251       15251            White               23   
15252       15252            Black               28   
15253       15253            White               39   
15254       15254            White               32   
15255       15255            White               33   
15256       15256            Black               28   
15257       15257            Black               27   
15258       15258            White               31   
15259       15259            White               35   
15260       15260            White               33   
15261       15261            Black               47   
15262       15262            Other               38   
15263       15263            White               31   
15265       15265            White               27   
15266       15266            White               58   
15267       15267            White               44   
15268       15268            White               42   

                   Name of Offender Place of Execution  \
0      NORMAN ELI                                    2   
1      WOODS JOHN                                    4   
2      GAMARRA CHARLES                               2   
3      DESAYAS VICTORIANO                            2   
4      NOREAGO FRANCISCO                             2   
5      DAVIS THOMAS                                  2   
6      WILSON HORATIO                                2   
7      DAVY                                          2   
8      BRIDEWELL WILLIAM                             2   
9      LESTER ED

In [19]:
df['Crimes Committed'] = df['Crimes Committed'].astype(int)

In [20]:
selected_features = df[['Crimes Committed', 'Year', 'State', 'County']]

In [21]:
selected_features.head()

Crimes Committed  Year  State  County
0                     1  1812      1      89
1                    44  1814      1       0
2                    13  1820      1      97
3                     1  1820      1      97
4                     1  1822      1      97
5                    39  1822      1     125
6                     1  1822      1      71
7                    15  1823      1      47
8                     1  1823      1      79
9                     1  1824      1      89
10                    1  1825      1      97
11                    1  1825      1     105
12                    1  1827      1     125
13                    1  1827      1      97
14                    1  1827      1     125
15                    2  1827      1     125
16                    1  1830      1     107
17                    1  1832      1     101
18                   22  1832      1      57
19                   37  1833      1     109
20                    1  1833      1      25
21                    1  1833      1       0
22                    1  1834      1     113
23                    1  1834      1     113
24                    1  1834      1      85
25                    2  1834      1     101
26                    1  1835      1      97
27                    1  1835      1      59
28                    1  1835      1      59
29                    1  1835      1      59
...                 ...   ...    ...     ...
15238                10  1999     51      41
15239                 6  1999     51      19
15240                10  1999     51     153
15241                10  1999     51     187
15242                 1  1999     51     159
15243                10  1999     51     143
15244                25  1999     51      15
15245                 6  1999     51     550
15246                24  1999     51      41
15247                10  1999     51     740
15248                 1  1999     51     650
15249                10  1999     51      41
15250                 1  2000     51     119
15251                10  2000     51      79
15252                 1  2000     51     153
15253                10  2000     51     810
15254                11  2000     51     810
15255                11  2000     51     710
15256                10  2000     51      59
15257                 1  2000     51     159
15258                10  2001     51      67
15259                19  2002     51     149
15260                24  2002     51     139
15261                25  2002     51     700
15262                 1  2002     51      59
15263                11  1993     53      11
15265                11  1998     53       5
15266                11  2001     53      61
15267                11  2000     54     183
15268                26  1992     56       0

[14833 rows x 4 columns]

In [22]:
dataset_array = selected_features.values
print(dataset_array.dtype)
print(dataset_array)

int64
[[   1 1812    1   89]
 [  44 1814    1    0]
 [  13 1820    1   97]
 ...
 [  11 2001   53   61]
 [  11 2000   54  183]
 [  26 1992   56    0]]


In [29]:
X = selected_features

In [30]:
# Create a kmeans model using k = 12
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=12)

In [31]:
# Fit the model to the data
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=12, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [32]:
# Use the data to predict the clusters
# save the predictions as `predicted_clusters`
predicted_clusters = kmeans.predict(X)

In [33]:
plt.scatter(X[:, 0], data[:, 1], c=predicted_clusters, s=50, cmap='viridis')

TypeError: '(slice(None, None, None), 0)' is an invalid key